eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
spring:
  
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/microservices_company
    username: postgres
server:
  port: 8082
management:
  context-path: /companyactuator
#spring:
 # profiles:
  #  active: prod
info:
  app:
    name: '{cipher}fa6b965e8ba672c148ab3884e64d7de114d5c2b4d5f2f7856bce24258eeca012'
    description: Spring company Actuator Working dev testing 12
logging:
  file: D:/logs/CompanyService/application_dev.log
  level:
    root: INFO
