eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka
server:
  port: 8081
management:
  context-path: /companyactuator
spring:
  profiles:
    active: prod
info:
  app:
    name: '{cipher}fa6b965e8ba672c148ab3884e64d7de114d5c2b4d5f2f7856bce24258eeca012'
    description: Spring company Actuator Working production testing Examples
